[platformio]
default_envs = nucleo_l476rg

[env:nucleo_l476rg]
platform = platformio/ststm32@19.7.1
board = nucleo_l476rg
framework = arduino

lib_deps =
    askuric/Simple FOC@2.4.0

upload_protocol = stlink
monitor_speed = 115200
monitor_filters = direct
